### ISSUE TITLE
Add files to conform to nf-core linter

### ISSUE THREAD

**Issue by j23414** [j23414/stubtest#1]
After trying out the nf-core linter:

```
  nf-core linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run nf-core linting
      uses: nf-core/gh-action-lint@master
      with:
          nextflow_version: '20.04.1'
          nfcore_version: '1.9'
          mode: 'release'
          GITHUB_COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_COMMIT: ${{ github.event.pull_request.head.sha }}
```

Check failed, and may need to add boilerplate for nf-core pipelines:

```
+ nf-core lint /github/workspace

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

Running pipeline tests

ERROR: Found test failures in 'check_files_exist', halting lint run.

INFO: =============================
          LINTING RESULTS
===================================
  [✔]    4 tests passed
  [!]    2 tests had warnings
  [✗]   10 tests failed

WARNING: Test Warnings:
  http://nf-co.re/errors#1 : File not found: environment.yml
  http://nf-co.re/errors#1 : File not found: conf/base.config

ERROR: Test Failures:
  http://nf-co.re/errors#1 : File not found: nextflow.config
  http://nf-co.re/errors#1 : File not found: Dockerfile
  http://nf-co.re/errors#1 : File not found: LICENSE or LICENSE.md or LICENCE or LICENCE.md
  http://nf-co.re/errors#1 : File not found: CHANGELOG.md
  http://nf-co.re/errors#1 : File not found: docs/README.md
  http://nf-co.re/errors#1 : File not found: docs/output.md
  http://nf-co.re/errors#1 : File not found: docs/usage.md
  http://nf-co.re/errors#1 : File not found: .github/workflows/branch.yml
  http://nf-co.re/errors#1 : File not found: .github/workflows/ci.yml
  http://nf-co.re/errors#1 : File not found: .github/workflows/linting.yml

ERROR: Sorry, some tests failed - exiting with a non-zero error code...
```
